[package]
name = "yorool_gui3"
version = "0.1.0"
authors = ["milyin <milyin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez="0.5.1"
async-trait = "0.1.24"
async-std="1.5.0"
